### ISSUE TITLE
`Bug`: Compile Fail may be success

### ISSUE THREAD

**Issue by dfuchss** [kit-sdq/programming-lecture-eclipse-artemis#181]
**Describe the bug**
Check that result is not marked as passed on compile error. (all for empty set)

**Comment by Shirkanesi** [comment]
Looked into it. Seems like there are two options:
1) Actually look for the buildlogs and try to figure out if the compile worked
2) Assert that there will always be any feedback whenever a build worked (this will be most likely the case hence typically everyone will have any kind of public-test; even ones with 0P seem to work). 
In this case it should be enough to add `&& feedbacks.size() > 0` in ResultTab line 239.
Me personally, I would prefer the second option because it's much more straight-forward.

**Comment by dfuchss** [comment]
Yes I would simply add !result.isEmpty() to the allSatisfy() :) Nice that you've looked into it.
