### ISSUE TITLE
`Feature` Multi-Language Support for Grading Buttons

### ISSUE THREAD

**Issue by dfuchss** [kit-sdq/programming-lecture-eclipse-artemis#259]
### Describe the solution you'd like

The Grading Config shall support multiple languages for the buttons (based on the language config of the user).
A possible solution would be adding two optional language dictionaries (maps) for the button label and the button description.
Nevertheless, the data send to the server shall **not** change. (It's just a change in the UI)

I.e., 
```json
        {
            "shortName": "jdEmpty",
            "button": "JavaDoc Leer",
            "message": "JavaDoc ist leer oder nicht vorhanden",

            "messages": {
                        "en": "JavaDoc is empty or not present"           
            }

            "buttons": {
                        "en": "JavaDoc Empty"
            }

            "penaltyRule": {
                "shortName": "thresholdPenalty",
                "threshold": 1,
                "penalty": 5
            },
            "appliesTo": "style"
        },
```

**Comment by Shirkanesi** [comment]
I'dd suggest embedding the information which language was used in the JSON send to Artemis.
This might help in the future for understanding why a penalty was given (as the exact wording might matter).

> Nevertheless, the data send to the server shall not change.
Whats the reasoning for that? If the student is using Artemis in English (detectable from within the tool) the comments could as well be provided in English. Or do you think this might be a problem due to "Prüfungssprache"?

**Comment by dfuchss** [comment]
users cannot change the language :( (and persist that)

this feature will just be used by the correctors. we will send the default information (german text) because we cannot determine the used language and because the lecture is in german
