### ISSUE TITLE
`Bug`:  Artemis crashes suddenly with `GSlice: assertion failed: sinfo->n_allocated > 0`

### ISSUE THREAD

**Issue by two-heart** [kit-sdq/programming-lecture-eclipse-artemis#290]
### Describe the bug

Crash

### Describe how to reproduce

How to reproduce/ how to avoid

1. Start ArtemisGrading from the command line.
2. Use it normally
3. After a time usually shorter than 3 minutes, ArtemisGrading crashes with the error message
```
***MEMORY-ERROR***: SWT[28827]: GSlice: assertion failed: sinfo->n_allocated > 0
```
Previous error messages vary, but usually involve some combination of multiple
```
(SWT:28827): Gtk-WARNING **: <time>: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)
```
and
```
(SWT:30700): Gtk-CRITICAL **: <time>: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```

The issue can be avoided by starting from the command line with the environment variable `G_SLICE=always-malloc` set:
```
G_SLICE=always-malloc ./ArtemisGrading
```

### Expected behavior

No crash

### Environment

Linux, x11, OpenJDK 18
ArtemisGrading v3.0.2

**Comment by Shirkanesi** [comment]
Not quite sure if this is related, however I feel like this only happens when the user is tabbing out of the tool and tabs back in.
I'm completely confused what exactly is going on but since I moved to using a dedicated device to respond to messages to prevent tabbing out of the grading tool, it never crashed again. For experimental purposes I tried tabbing out and answering messages; then it crashed again...
Really confusing issue.

**Comment by Shirkanesi** [comment]
Happened again. This time without tabbing out of the tool :(

**Comment by dfuchss** [comment]
I think we should simply add G_SLICE=always-malloc to the run args on Linux systems. I'll have a look at that these days

**Comment by dfuchss** [comment]
We will move to intelligrade in the future. Thus this project will be archived then :)
